### PR TITLE
Bug/TurnOffAutomaticallyWithNewDay

### LINKED ISSUE #4: HealthCheck triggers continously
So, I finally got it working with teams and manually. 

Thank you, it's a nice "little" project - you put a lot of work in it.

However it turns out, that regularly the light turns off after about 5-10 seconds,
the log showing it als caused due to a health check.

I can turn it on again by toggling between manual and teams mode again, but it will most likely turn off again several seconds later.
Sometimes it works stable and then again: Back to the described error cycle.

Are there any known workarounds / solutions? Is this a connection / time lag problem?
Is it possible to make this check a bit more robust?

```
`23:42:34.003 | EventThread COM8 | DEBUG | d.d.u.u.UsbAdapter | Update to color '0xffa500ff'. |
23:42:34.010 | EventThread COM8 | DEBUG | d.d.u.u.UsbAdapter | Data is available. |
23:42:34.010 | EventThread COM8 | INFO  | d.d.u.u.UsbAdapter | Successfully transmitted image. |

**23:42:39.091 | Health | INFO  | d.d.u.v.ConfigurationView | Turn off automatically at '01:42:33.747380700' |**

23:42:39.515 | UsbAdapterActionQueue Thread | DEBUG | d.d.u.u.UsbAdapter | Start execution of action. |
23:42:39.564 | EventThread COM8 | DEBUG | d.d.u.u.UsbAdapter | Data is available. |
23:42:39.564 | EventThread COM8 | INFO  | d.d.u.u.UsbAdapter | Device is ready for image change. |
23:42:39.564 | EventThread COM8 | DEBUG | d.d.u.u.UsbAdapter | Update to color '0x000000ff'. |'
```

### PR DESCRIPTION
**Pull request by mairKi**

### CODE REVIEW

File: src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java [hunk 1]
```diff
@@ -430,9 +432,23 @@ void refreshButton() {
...
+         timedOut = false;
+         startDate = currentDate;
+      }
+
+      LocalDate turnOffDate = startDate;
+      if (timeLightsTurnedOff.isBefore(timeLightsTurnedOffNow)) {
+         turnOffDate = turnOffDate.plusDays(1);
+      }
+
+      LocalDateTime turnOffDateTime = LocalDateTime.of(turnOffDate, timeLightsTurnedOff);
```
Comment (Death111) [inline src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java]: can't we use LocalDateTime from the start? so that we only have LocalDateTime and not one localDate and one LocalTime to represent a date and a time?

File: src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java [hunk 2]
```diff
@@ -139,7 +141,7 @@ public class ConfigurationView {
             LOG.debug("Reconnection check was interrupted.", e);
             return;
          }
-         turnOffAutomaticallyIfNeeded(LocalTime.now());
+         turnOffAutomaticallyIfNeeded(LocalTime.now(),LocalDate.now());
```
Comment (Death111) [inline src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java]: does not look like the code was formatted correctly

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java [hunk 3]
```diff
@@ -124,39 +125,58 @@ void shouldLeaveTimeoutWhenColorChanges() {
...
       configurationView.setUsbAdapter(usbAdapter);
       CommandLineOptions.setTimeoutInMinutes(60);
-      configurationView.timeLightsTurnedOffNow = LocalTime.of(20, 0);
+      configurationView.timeLightsTurnedOffNow = LocalTime.of(21, 0);
       // When
-      configurationView.turnOffAutomaticallyIfNeeded(currentTime);
+      configurationView.turnOffAutomaticallyIfNeeded(currentTime, LocalDate.now());
       // Then
-      verify(usbAdapter).updatePixel(Color.BLACK);
+      verify(usbAdapter, never()).updatePixel(Color.BLACK);
```
Comment (Death111) [inline src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java]: - You did change an existing test (is the previoius test case not valid anymore?)
- test name does not reflect what the test is testing

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java [hunk 4]
```diff
@@ -124,39 +125,58 @@ void shouldLeaveTimeoutWhenColorChanges() {
...
    }
 
+   @Test
+   void shouldGoOutIfTheTimeIsExceededOnTheNextday() {
+      // Given
+      final LocalTime currentTime = LocalTime.of(23,42,39,91);
+      configurationView.setUsbAdapter(usbAdapter);
+      CommandLineOptions.setTimeoutInMinutes(60);
+      LocalDate startDate = LocalDate.now().plusDays(1);
+      configurationView.timeLightsTurnedOffNow = LocalTime.of(01,42,33,747380700);
```
Comment (Death111) [inline src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java]: the test setup does only setup a time when it should turn off - but not a date. seems it is not known at what date it should turn off? hard to understand (or i am just confused)

**Review by Death111 — CHANGES_REQUESTED** [review]

File: src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java (hunk 2 above)
Comment (mairKi) [reply src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java]: Done.

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java (hunk 3 above)
Comment (mairKi) [reply src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java]: Done

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java [hunk 5]
```diff
@@ -107,15 +116,18 @@ void shouldOnlyTurnOffOnceWhenCurrentTimeExceedsTheTimeoutTwice() {
...
       configurationView.setUsbAdapter(usbAdapter);
       CommandLineOptions.setTimeoutInMinutes(60);
       configurationView.timeLightsTurnedOffNow = LocalTime.of(20, 0);
 
       // When
-      configurationView.turnOffAutomaticallyIfNeeded(currentTime);
+      configurationView.turnOffAutomaticallyIfNeeded(dateTime);
       model.setColor(model.colorProperty().getValue().invert());
-      configurationView.turnOffAutomaticallyIfNeeded(laterCurrentTime);
+      configurationView.turnOffAutomaticallyIfNeeded(dateTime);
```
Comment (Death111) [inline src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java]: u did change a variable here. it was not the same date as in the call before,

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java (hunk 3 above)
Comment (Death111) [reply src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java]: I do not see any change done here?

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java [hunk 6]
```diff
@@ -124,39 +136,69 @@ void shouldLeaveTimeoutWhenColorChanges() {
...
+
+      LocalDateTime timeoutDateTime = LocalDateTime.of(currentDate.plusDays(1), LocalTime.of(0, 42, 33, 747380700));
+
+      configurationView.timeLightsTurnedOffNow = timeoutDateTime.toLocalTime();
+
+      // When
+      configurationView.turnOffAutomaticallyIfNeeded(dateTime);
+
+      // Then
+      verify(usbAdapter).updatePixel(Color.BLACK);
```
Comment (Death111) [inline src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java:170]: I'm not sure about the test. As I understand the setup
- now is the 23.12.2024 23:42
- it should turn off on the 24.12.2024 00:42

and when you trigger this you assert that it should have turned off - besides the turn of date was not reached? Or did I understand the test wrong?

File: src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java [hunk 7]
```diff
@@ -430,9 +432,26 @@ void refreshButton() {
       }
    }
```
Comment (Death111) [inline src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java:430]: why is the class field `timeLightsTurnedOffNow` still only LocalTime? why is it not LocalDateTime? Do we need this like it?

**Review by Death111 — CHANGES_REQUESTED** [review]

File: src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java [hunk 8]
```diff
@@ -430,9 +432,26 @@ void refreshButton() {
...
 
-   void turnOffAutomaticallyIfNeeded(final LocalTime currentTime) {
+   void turnOffAutomaticallyIfNeeded(final LocalDateTime currentLocalDateTime) {
       final LocalTime timeLightsTurnedOff = timeLightsTurnedOffNow.plusMinutes(CommandLineOptions.getTimeout());
-      if (!currentTime.isBefore(timeLightsTurnedOff) && !timedOut) {
+
```
Comment (Death111) [inline src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java]: this logic seems very complicated. I expected basically the same logic than before but using LocalDateTime instead of LocalTime. Do we need all this additional logic?

Comment (mairKi) [reply src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java]: Done.

File: src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java (hunk 7 above)
Comment (mairKi) [reply src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java:430]: Done is now LocalDateTime

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java (hunk 4 above)
Comment (mairKi) [reply src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java]: Done.

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java (hunk 3 above)
Comment (mairKi) [reply src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java]: I have changed the name

Comment (mairKi) [reply src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java]: Did the old test again

File: src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java (hunk 6 above)
Comment (mairKi) [reply src/test/java/de/doubleslash/usb_led_matrix/view/ConfigurationViewTest.java:170]: Done.

File: src/main/resources/log4j2.xml [hunk 9]
```diff
@@ -29,7 +29,7 @@
         </RollingFile>
     </Appenders>
     <Loggers>
-        <Root level="info">
+        <Root level="debug">
```
Comment (Death111) [inline src/main/resources/log4j2.xml]: why debug as default level?

File: src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java [hunk 10]
```diff
@@ -430,10 +429,10 @@ void refreshButton() {
...
    }
 
-   void turnOffAutomaticallyIfNeeded(final LocalTime currentTime) {
-      final LocalTime timeLightsTurnedOff = timeLightsTurnedOffNow.plusMinutes(CommandLineOptions.getTimeout());
-      if (!currentTime.isBefore(timeLightsTurnedOff) && !timedOut) {
-         LOG.info("Turn off automatically at '{}'", timeLightsTurnedOff);
+   void turnOffAutomaticallyIfNeeded(final LocalDateTime currentLocalDateTime) {
+      final LocalDateTime timeLightsTurnedOff = timeLastColorChange.plusMinutes(CommandLineOptions.getTimeout());
+      if (!currentLocalDateTime.isBefore(timeLightsTurnedOff) && !timedOut) {
+         LOG.info("turn of '{}'", timeLightsTurnedOff);
```
Comment (Death111) [inline src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java]: Log statement before seemed more meaningful, or?

**Review by Death111 — CHANGES_REQUESTED** [review]

File: src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java (hunk 10 above)
Comment (mairKi) [reply src/main/java/de/doubleslash/usb_led_matrix/view/ConfigurationView.java]: Done.

File: src/main/resources/log4j2.xml (hunk 9 above)
Comment (mairKi) [reply src/main/resources/log4j2.xml]: Done.

**Review by Death111 — APPROVED** [review]
